### ISSUE TITLE
How do you FLUID?

### ISSUE THREAD

**Issue by M0JXD** [Stazed/ntk#2]
Hi again Stazed,

While working some more on a Non-Sequencer fork I've found that when opening the .fl files in fluid (not just generating code with the -c option) it automatically causes changes that break the app. This happens with ntk-fluid and FLUID 1.3.8 which I have on my machine.

I think this is a versioning issue as prior to my tampering the .fl files had been unedited since early March 2012, but there where some changes to ntk-fluid made in the months after that (e.g. removing XDBE and Forms compatibility) and of course FLTK's version changed too. I've ended up just carefully applying the changes I require to the .fl file but this difficult and clearly not a long term solution.

When editing .fl files which version of FLUID do you use? As you're supporting both FLTK and NTK in Timeline and Mixer it seems like a pain point for cross compatibility. Ideally I want to work with just one version so I can fix this issue for that.

**Comment by Stazed** [comment]
I use the FLTK 1.3 x (any) version. Also worked with 1.4.  I have not had any problems with it. It does make some changes but they don't break anything. I suspect that it works because the timeline and mixer were kept more current? Oh, if the .fl has some of the NTK specific box types, like ASYM, you may need to modify things if using FLTK fluid. I really do not know why NTK fluid would not work, seems like it should.

**Comment by M0JXD** [comment]
Thank you for letting me know. Now you have the GTK theme and a Vector theme (I really like this one! Great work!!) I'm even more inclined for a FLTK build so I'll fix against the same 1.3.x FLUID you use. It's only a minor problem it causes, it starts on the wrong tab. It changes a bunch of numbers too so I want to double check those changes are sane.

There's no ASYM boxes in Sequencer, given that the fl files look to have been unedited since prior to NTK's introduction I think it might not use any NTK specific widgets. Thanks for your help.
